version: '3'

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos-quick
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    restart: always
  redis:
    image: redis
    container_name: redis-quick
    ports:
      - "6379:6379"
    restart: always
  mysql:
    image: mysql
    container_name: mysql-quick
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
    ports:
      - "3306:3306"
    restart: always