import { MenuInfo } from '.';

const menus: Array<MenuInfo> = [
  {
    appName: 'react-app',
    url: '/',
    title: 'react-app1',
    icon: 'icon-react',
    id: 'react-app1',
    openType: 'tab',
    params: {},
  },
  {
    appName: 'react-app',
    url: '/about',
    title: 'about',
    id: 'react-app2',
    icon: 'icon-vue',
    openType: 'tab',
    params: {},
  },
  {
    appName: 'card-app',
    url: '/',
    title: 'card-laboutEditor',
    id: 'card-app2',
    icon: 'icon-vue',
    openType: 'tab',
    params: {},
  },
  {
    appName: 'react-app',
    url: '/detail/asdss',
    title: 'detail asdss',
    id: 'react-cardEditor1',
    icon: 'icon-vue',
    openType: 'tab',
    params: {},
  },
  {
    appName: 'card-app',
    url: '/cardEditor',
    title: 'cardEditor',
    id: 'react-cardEditor',
    icon: 'icon-vue',
    params: {},
    openType: 'tab',
  },
  {
    appName: 'card-app-iframe-window',
    url: 'http://localhost:3002/cardEditor',
    title: 'card-app-iframe-window',
    id: 'card-app-iframe-window',
    icon: 'icon-vue',
    params: {},
    openType: 'window',
    isIframe: true,
  },
  {
    appName: 'card-app-iframe-tab',
    url: 'http://localhost:3002/cardEditor',
    title: 'card-app-iframe-tab',
    id: 'card-app-iframe-tab',
    icon: 'icon-vue',
    params: {},
    openType: 'tab',
    isIframe: true,
  },
];
export default menus;
